server:
  port: 8887

github:
  client:
    id: Iv1.3273c2174f5269f6
    secret: 1b9480a22d459e98585188b7c1366ddf48547542
  redirect:
    uri: http://localhost:8887/callback


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zzh.community.model

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
